# Generated by Django 6.0 on 2026-07-10 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
        ("themes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="portfolios",
                to="themes.theme",
            ),
        ),
    ]
